version: '3'
services:
  collector:
    image: otel/opentelemetry-collector-contrib:0.57.2
    volumes:
      - ./otel-config.yaml:/otel-config.yaml
    command: ["/otelcol-contrib", "--config=/otel-config.yaml", "${OTELCOL_ARGS}"]
    environment:
      LOG_EXPORTER_LOG_LEVEL: "INFO"
      NEW_RELIC_API_KEY: "${NEW_RELIC_API_KEY}"
    ports:
      - "4317:4317"     # grpc
      - "13133:13133"   # health
      - "8006:8006"     # fluentdforward
      - "8006:8006/udp" # fluentforward
  my_fluentd:
    image: fluent/fluentd:v1.1.1-onbuild
    depends_on:
      - collector
    volumes:
      - $PWD/fluentd:/fluentd/etc
    environment:
      - OTEL_COLLECTOR_HOSTNAME=collector
      - OTEL_COLLECTOR_PORT=8006
    ports:
      - "24224:24224"
  otel-service:
    restart: on-failure
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - collector
      - my_fluentd
    environment:
      - DEBUG
      - OTEL_SERVICE_NAME=wcp-otel-service
      - OTEL_RESOURCE_ATTRIBUTES=service.instance.id=otel-123456789
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://collector:4317
      - spring.main.banner-mode=off
      - FLUENTD_HOST=my_fluentd
      - FLUENTD_PORT=24224
    logging:
      driver: fluentd
      options:
        fluentd-address: my_fluentd
        tag: docker.{{.ID}}